# Lecture 1  

```{block2 items, type='rmdnote'}
Need for designing of experiments, characteristics of a good design. Basic principles of designs - randomization, replication and local control  
```  
## Design of experiments  
Any scientific investigation involves formulation of certain assertions (or hypotheses) whose validity is examined through the data generated from an experiment conducted for the purpose. The term '*experiment*'is defined as the systematic procedure carried out under controlled conditions in order to discover an unknown effect, to test or establish a hypothesis, or to illustrate a known effect.  

Experiments can be designed in many different ways to collect information. **Design of experiments** (DOE) is a systematic method to determine the relationship between factors affecting a process and the output of that process. In other words, it is used to find cause-and-effect relationships.  

DOE is a structured approach for conducting experiments. Mainly aims at  

- Validity  

- Reliability  

- Replicability  

- Optimality  


Design of experiment means how to design an experiment. In the sense that how the observations or measurements should be obtained to answer a query in a valid, efficient and economical way. The designing of experiment and the analysis of obtained data are inseparable. If the experiment is designed properly keeping in mind the question, then the data generated is valid and proper analysis of data provides the valid statistical inferences. If the experiment is not well designed, the validity of the statistical inferences is questionable and may be invalid.  

## Importance of DoE  
* Reduce, control and provides an estimate of the experimental Error  

* Gives a structured approach  

* It reduce cost of experiment with considerable reliability  
* Produces statistically valid results  

* Allows to accommodate changes  

* Reduce complexity  

* Improves accountability  

## Characteristics of a good design  

- Provides unbiased estimates of the factor effects and associated uncertainties  

- Enables the experimenter to detect important differences  

- Includes the plan for analysis and reporting of the results  
- Gives results that are easy to interpret  

- Permits conclusions that have wide validity  

- Minimal resource usage  

- Is as simple as possible

 


